### ISSUE TITLE
Error in COCO Dataset 

### ISSUE THREAD

**Issue by tammy3107** [TobiasSunderdiek/cartoon-gan#1]
The dataset that you have linked in the project is giving errors. I had to download the original dataset from the official site again to make it work. Please look into this matter.

**Comment by TobiasSunderdiek** [comment]
Thank you for opening this issue, I just tested README-Step 1 to download the coco-data from the reference [3] in README: http://images.cocodataset.org/annotations/annotations_trainval2017.zip. With Google Chrome, download finished with no errors.
Can you please provide me some additional information to reproduce the issue? 
Thanks in advance!

**Comment by tammy3107** [comment]
Actually when I downloaded it and tried to open with Coco API it was giving error that 'can't load the annotations then I redownloaded the dataset from the Coco website and it was not giving error

**Comment by TobiasSunderdiek** [comment]
Thank you, my documentation in https://tobiassunderdiek.github.io/cartoon-gan/#tc1_3 was very misleading, I just corrected it.
After downloading and unzipping the annotations, please configure in file `cartoon-gan/phot_downloader.py` the path where the unzipped annotations folder lies, https://github.com/TobiasSunderdiek/cartoon-gan/blob/master/photo_downloader.py#L7

**Comment by TobiasSunderdiek** [comment]
Documentation updated

**Comment by TobiasSunderdiek** [comment]
I hope this helps to solve your issue?

**Comment by tammy3107** [comment]
Yeah thanks a lot

**Comment by TobiasSunderdiek** [comment]
Great, thank you for helping me making this repo better by having opened this issue!

I'll close it now, best regards
