### ISSUE TITLE
I don't understand. could you please help?

### ISSUE THREAD

**Issue by putuoka** [TobiasSunderdiek/cartoon-gan#2]
I have successfully run till the Photo step in google colab research https://i.imgur.com/YSVAxQt.png
but the picture remind the same as original also when continue next step i face an error in training section.

could you please make it simple for newbie like me please

**Comment by TobiasSunderdiek** [comment]
Hi @putuoka 
first of all, sorry for the late reply! I just saw your issue.

Can you please give me the error message you face in the training section? I will investigate it.

Thanks in advance and best regards!

**Comment by putuoka** [comment]
> Hi @putuoka
> first of all, sorry for the late reply! I just saw your issue.
> 
> Can you please give me the error message you face in the training section? I will investigate it.
> 
> Thanks in advance and best regards!

Hi sorry it was resolve. Thank you

**Comment by TobiasSunderdiek** [comment]
Hi @putuoka ,
great that it is resolved!
thank you for your reply and for adding this issue in general...every issue helps me to make this repo better, so thank you again!
Best regards
